---
- name: Creates ssh-clients group for ssh access
  group:
    name=ssh-clients
    state=present

- name: Add current remote_user to the ssh-clients group
  user:
    name="{{ ansible_ssh_user }}"
    append=yes
    groups=ssh-clients

- name: Ensure the AllowGroups declarative exists
  lineinfile:
    dest=/etc/ssh/sshd_config
    line='AllowGroups ssh-clients'

