---
- include: 10-chruby.yml                      tags=chruby
- include: 20-ruby-install.yml                tags=chruby
- include: 30-ruby.yml                        tags=chruby
- include: 40-remove-outdated-rubies.yml      tags=chruby
- include: 50-configure-system-chruby.yml     tags=chruby
- include: 60-enable-ruby-access-for-root.yml tags=chruby
