---
- hosts: all
  sudo: yes
  roles:
    - basic-setup
    - chruby
    - bootstrap-remote-user
    - postfix-relay
    - passenger-nginx
    - nodejs
    - aris-user-management
    - selenium-webdriverio
    - jenkins
