---
- hosts: all
  sudo: yes
  gather_facts: yes
  roles:
    - basic-setup
    - chruby
    - bootstrap-remote-user
    - postfix-relay
    - passenger-nginx
    - nodejs
    - aris-server
    - jenkins
    - munin
    - file-hosting
    - gitlist
    - portal-revealjs
    - capybara-poltergeist
    - papertrail_remote_syslog2
