---
- name: Rename latest apps.yml to apps.processing.yml
  shell: >
    test -e /opt/aris/config/apps.yml && mv /opt/aris/config/apps.yml /opt/aris/config/apps.processing.yml; true

- stat:
    path=/opt/aris/config/apps.processing.yml
  register: apps_file

- include_vars: /opt/aris/config/apps.processing.yml
  when: apps_file.stat.exists

