- include: 10-app-account-with-ssh.yml
- include: 20-app-access-to-chruby.yml
# - include: 30-postgres-account-and-database.yml
- include: 40-app-skeleton.yml
- include: 50-app-git-config.yml
- include: 60-app-access-to-env-vars.yml
- include: 70-nginx-passenger-config.yml
- include: 80-update-app-status.yml
- include: 90-symlink-git-for-ginatra.yml
